C-Sharp/C Sharp lektioner/Lektion 10 - Web/Models/Person.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Lektion_10___Web.Models
{
    public class Person
    {
        string Name { get; set; }
        string Addresse { get; set; }
        int Alder { get; set; }
        string Information { get; set; }

        public Person(string navn, string addresse, int alder, string info)
        {
            Name = navn;
            Addresse = addresse;
            Alder = alder;
            Information = info;
        }
    }
}

C-Sharp/C Sharp lektioner/Lektion 10 - Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lektion_10___Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

C-Sharp/C Sharp lektioner/Lektion 10 - Web/Controllers/MainAppController.cs
using Lektion_10___Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lektion_10___Web.Controllers
{
    public class MainAppController : Controller
    {
        Person p1 = new Person("John", "Resedavej 49", 30, "Test");
        // GET: MainApp
        public ActionResult Index()
        {
            return View();
        }
        public string DemoAction()
        {
            return "Hello from DemoAction";
        }
        public ActionResult DemoActionTool()
        {
            return View();
        }
        public ActionResult AboutMe()
        {
            return View();
        }
        public ActionResult Download()
        {
            return View();
        }
        public ActionResult PersonPage(string option)
        {
            return View(option);
        }

    }
}

C-Sharp/C Sharp lektioner/Lektion 10 - Web/Views/MainApp/AboutMe.cshtml
@model Lektion_10___Web.Models.Person
@{
    ViewBag.Title = "Contact Information";
}

<div class="wrapper row2">
    <div id="container" class="clear">
        <!-- ####################################################################################################### -->
        <!-- ####################################################################################################### -->
        <!-- ####################################################################################################### -->
        <!-- ####################################################################################################### -->
        <div id="about-us" class="clear">
            <div class="three_fifth first">
                <!-- ####################################################################################################### -->
                <section id="about-intro" class="clear">
                    <div class="panorama"><img class="imgholder" src="images/demo/548x250.gif" alt=""></div>
                    <p>
                        Praesent imperdiet justo at sem. Nam accumsan dui eget diam.Nulla quis ante eget pede fringilla rutrum. Proin mollis tristique orci.
                        Nam est. Fusce felis nisl, volutpat vel, sollicitudin eu, luctus sit amet, sem.
                    </p>
                    <p>
                        Curabitur risus erat, scelerisque sit amet, mollis id, consectetuer eu, neque. Curabitur sodales semper arcu.
                        Sed ullamcorper arcu eu ante. Vestibulum sed lacus. Quisque vitae libero. Sed quis turpis vitae lectus vehicula tincidunt.
                        Aliquam quam mi, rutrum malesuada, consequat vitae, accumsan ut, lacus. Nulla dictum vestibulum lorem.
                    </p>
                </section>
                <!-- ####################################################################################################### -->
                <section id="skillset" class="clear">
                    <div class="fl_left first">
                        <h2>Vivamuslibero Auguer</h2>
                        <p>Lorem ipsum dolor sit amet, consectetaur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua ut enim ad minim veniam.</p>
                        <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                    </div>
                    <div class="fl_left">
                        <h2>Vivamuslibero Auguer</h2>
                        <ol>
                            <li><a href="#">Aliquam venenatis leo et orci.</a></li>
                            <li><a href="#">Vivamus eleifend sollicitudin eros.</a></li>
                            <li><a href="#">Maecenas vitae nunc.</a></li>
                            <li><a href="#">Ut pretium odio eu nisi.</a></li>
                            <li><a href="#">Nam condimentum mi id magna.</a></li>
                            <li><a href="#">Pellentesque consectetuer, felis vel.</a></li>
                        </ol>
                    </div>
                </section>
                <!-- ####################################################################################################### -->
            </div>
            <!-- ####################################################################################################### -->
            <section id="team" class="two_fifth">
                <h2>Vivamuslibero Auguer</h2>
                <ul>
                    <li id="Person1">
                        <figure class="clear">
                            <a href="/MainApp/PersonPage/Person1"><img src="../../images/demo/team-member.gif" alt=""  )></a>
                            <figcaption>
                                <p class="team_name">Name Goes Here</p>
                                <p class="team_title">Job Title Here</p>
                                <p class="team_description">Vestassapede et donec ut est liberos sus et eget sed eget. Quisqueta habitur augue magnisl magna phas ellus.</p>
                            </figcaption>
                        </figure>
                    </li>
                    <li>
                        <figure class="clear">
                            <img src="../../images/demo/team-member.gif" alt="">
                            <figcaption>
                                <p class="team_name">Name Goes Here</p>
                                <p class="team_title">Job Title Here</p>
                                <p class="team_description">Vestassapede et donec ut est liberos sus et eget sed eget. Quisqueta habitur augue magnisl magna phas ellus.</p>
                            </figcaption>
                        </figure>
                    </li>
                    <li>
                        <figure class="clear">
                            <img src="../../images/demo/team-member.gif" alt="">
                            <figcaption>
                                <p class="team_name">Name Goes Here</p>
                                <p class="team_title">Job Title Here</p>
                                <p class="team_description">Vestassapede et donec ut est liberos sus et eget sed eget. Quisqueta habitur augue magnisl magna phas ellus.</p>
                            </figcaption>
                        </figure>
                    </li>
                    <li>
                        <figure class="clear">
                            <img src="../../images/demo/team-member.gif" alt="">
                            <figcaption>
                                <p class="team_name">Name Goes Here</p>
                                <p class="team_title">Job Title Here</p>
                                <p class="team_description">Vestassapede et donec ut est liberos sus et eget sed eget. Quisqueta habitur augue magnisl magna phas ellus.</p>
                            </figcaption>
                        </figure>
                    </li>
                    <li>
                        <figure class="clear">
                            <img src="../../images/demo/team-member.gif" alt="">
                            <figcaption>
                                <p class="team_name">Name Goes Here</p>
                                <p class="team_title">Job Title Here</p>
                                <p class="team_description">Vestassapede et donec ut est liberos sus et eget sed eget. Quisqueta habitur augue magnisl magna phas ellus.</p>
                            </figcaption>
                        </figure>
                    </li>
                </ul>
            </section>
            <!-- ####################################################################################################### -->
        </div>
        <!-- ####################################################################################################### -->
        <!-- ####################################################################################################### -->
        <!-- ####################################################################################################### -->
        <!-- ####################################################################################################### -->
    </div>
</div>

C-Sharp/C Sharp lektioner/Lektion 10 - Web/Views/MainApp/DemoActionTool.cshtml
@{
    ViewBag.Title = "DemoActionTool";
}

<h2>DemoActionTool</h2>

C-Sharp/C Sharp lektioner/Lektion 10 - Web/Views/MainApp/Download.cshtml
@{
    ViewBag.Title = "Download";
}

<h2>Download</h2>

C-Sharp/C Sharp lektioner/Lektion 10 - Web/Views/MainApp/PersonPage.cshtml
@{
    ViewBag.Title = "PersonPage";
}

<h2>@ViewBag.</h2>

C-Sharp/C Sharp lektioner/Lektion 10 - Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Demo", "DemoActionTool", "MainApp")</li>
                    <li>@Html.ActionLink("Contact Info", "AboutMe", "MainApp")</li>
                    <li>@Html.ActionLink("Download", "Download", "MainApp")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Rendered by ASP.Net - Controlled by John Høeg</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>